from __future__ import annotations

from stackbox.config_gen.base import ServiceConfigGenerator

SERVICES_WITH_DB = [
    "keystone",
    "glance",
    "nova",
    "nova_api",
    "nova_cell0",
    "neutron",
    "placement",
    "ironic",
]

CONDITIONAL_DBS = {
    "cinder": lambda job: job.devstack_services.get("c-api", False),
}


class MariaDBConfigGenerator(ServiceConfigGenerator):

    def generate(self) -> dict[str, str]:
        db_pass = self._db_pass().replace("\\", "\\\\").replace("'", "\\'")
        lines = [
            "-- Generated by STACKBOX",
            "",
        ]

        all_dbs = list(SERVICES_WITH_DB)
        for db_name, condition in CONDITIONAL_DBS.items():
            if condition(self.job):
                all_dbs.append(db_name)

        for db in all_dbs:
            lines.append(f"CREATE DATABASE IF NOT EXISTS `{db}` CHARACTER SET utf8mb4;")
            lines.append(
                f"GRANT ALL PRIVILEGES ON `{db}`.* TO '{db}'@'%'"
                f" IDENTIFIED BY '{db_pass}';"
            )
            lines.append("")

        lines.append("FLUSH PRIVILEGES;")
        lines.append("")

        return {"init.sql": "\n".join(lines)}
